Remove colors and run lint on all files on githooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,37 +1,22 @@
 #!/usr/bin/env sh
-RED="\033[1;31m"
-BLUE="\033[34m"
-GREEN="\033[1;32m"
-NOCOLOR="\033[0m"
 
-echo "${BLUE}(pre-commit) Cleaning compiled files...${NOCOLOR}"
+echo "(pre-commit) Cleaning compiled files..."
 npm run clean
 
-echo "${BLUE}(pre-commit) Building backend...${NOCOLOR}"
+echo "(pre-commit) Building backend..."
 npm run build:backend
 
 linter_exit_code=0
-eslint_files=$(git diff --cached --diff-filter=d --name-only --line-prefix=`git rev-parse --show-toplevel`/ | grep '.js$\|.ts$\|.vue$')
-stylelint_files=$(git diff --cached --diff-filter=d --name-only --line-prefix=`git rev-parse --show-toplevel`/ | grep '.css$\|.vue$')
 
-echo "${BLUE}(pre-commit) Running linters...${NOCOLOR}"
-if [ "$eslint_files" ]
-then
-  eslint --fix $eslint_files
-  linter_exit_code=$?
-fi
-
-if [ "$stylelint_files" ]
-then
-  stylelint --fix $stylelint_files
-  linter_exit_code=$(($? < $linter_exit_code ? $linter_exit_code : $?))
-fi
+echo "(pre-commit) Running linters..."
+npm run lintfix
+linter_exit_code=$?
 
 if [ $linter_exit_code -ne 0 ]
 then
-  echo "${RED}❌ (pre-commit) Please fix linting errors before committing!"
+  echo "❌ (pre-commit) Please fix linting errors before committing!"
   exit 1
 else
-  echo "${GREEN}✔ (pre-commit) ESlint and Stylelint did not find any errors!"
+  echo "✔ (pre-commit) ESlint and Stylelint did not find any errors!"
   exit 0
 fi
